apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-platform-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/leandromartinelli-cloud/enterprise-azure-gitops-platform.git
    targetRevision: main
    path: argocd/platform

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true