name: Platform Validation

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: Validate Private AKS Platform

    runs-on:
      - self-hosted
      - Linux
      - X64
      - azure
      - private

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login with managed identity
        run: |
          az login --identity --output none
          az account set --subscription "ecfc68ac-997b-48cc-981a-4ed575ae99ec"
          echo "Managed Identity authentication successful."

      - name: Install Kubernetes CLI tools
        run: |
          KUBECTL_VERSION="$(curl -L -s https://dl.k8s.io/release/stable.txt)"

          curl -L \
            "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" \
            -o /tmp/kubectl

          sudo install \
            -m 0755 \
            /tmp/kubectl \
            /usr/local/bin/kubectl

          kubectl version --client

          KUBELOGIN_VERSION="v0.2.12"

          curl -L \
            "https://github.com/Azure/kubelogin/releases/download/${KUBELOGIN_VERSION}/kubelogin-linux-amd64.zip" \
            -o /tmp/kubelogin.zip

          unzip -o /tmp/kubelogin.zip -d /tmp/kubelogin

          sudo install \
            -m 0755 \
            /tmp/kubelogin/bin/linux_amd64/kubelogin \
            /usr/local/bin/kubelogin

          kubelogin --version

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group rg-enterprise-gitops-dev-brazilsouth \
            --name aks-enterprise-gitops-dev-brazilsouth \
            --overwrite-existing

      - name: Validate nodes
        run: kubectl get nodes -o wide

      - name: Validate workloads
        run: kubectl get pods -A

      - name: Validate Argo CD applications
        run: kubectl get applications -A